name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: compiler
      shell: cmd
      run: |
        move /y C:\mingw64 C:\mingw64_
        call pull-mingw
    - name: source
      shell: cmd
      run: |
        set PATH=C:\Program Files\Git\cmd;%PATH%
        if not exist zlib (
            git clone https://github.com/madler/zlib.git
            pushd zlib
                git checkout v1.3.1
            popd
        )
    - name: build
      shell: cmd
      run: |
        set PATH=C:\mingw1310_64\bin;%PATH%
        pushd zlib
            if not exist build mkdir build
            pushd build
                cmake -G "Ninja" -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=C:/zlib-1.3.1 ..
                cmake --build .
                cmake --install .
            popd
        popd
        7z a -y zlib-1.3.1.zip C:\zlib-1.3.1
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: zlib-1.3.1
        path: C:\zlib-1.3.1
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: zlib-1.3.1.zip
